# Generated by Django 5.2.17 on 2026-10-01 03:55

import apps.rentals.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('room', 'Room'), ('house', 'House')], default='apartment', max_length=20)),
                ('landlord_name', models.CharField(blank=True, max_length=150)),
                ('landlord_phone', models.CharField(blank=True, max_length=30)),
                ('landlord_email', models.EmailField(blank=True, max_length=254)),
                ('meter_reading_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month when meter readings are due.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lease', 'Lease'), ('renewal', 'Renewal'), ('receipt', 'Receipt'), ('condition', 'Condition photo'), ('meter', 'Meter photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(max_length=255, upload_to=apps.rentals.models.document_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(help_text='Bytes')),
                ('room', models.CharField(blank=True, help_text='Condition photos: which room.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('taken_on', models.DateField(blank=True, help_text='Condition photos: when the photo was taken.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rentals.property')),
            ],
            options={
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rent_due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('terms', models.TextField(blank=True, help_text='Key terms: who pays utilities, notice period, rent increases.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Replaced by renewal')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous', models.OneToOneField(blank=True, help_text='The contract this one renews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal', to='rentals.contract')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rentals.document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rentals.property')),
            ],
            options={
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, help_text='kWh, m³, Gcal...', max_length=20)),
                ('has_meter', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='rentals.property')),
            ],
            options={
                'verbose_name_plural': 'utilities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rent', 'Rent'), ('utility', 'Utility bill'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('period', models.DateField(blank=True, help_text='First day of the month this payment covers.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rentals.contract')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rentals.document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.property')),
                ('utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rentals.utility')),
            ],
            options={
                'ordering': ('due_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reading_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rentals.document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='rentals.property')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='rentals.utility')),
            ],
            options={
                'ordering': ('-reading_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_reminder_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='unique_utility_name_per_property'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['property', 'due_date'], name='rentals_pay_propert_ce5a14_idx'),
        ),
    ]
