# Generated by Django 5.2.17 on 2026-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_landlord_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='item',
            field=models.CharField(blank=True, help_text='Condition photos: sofa, table...', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='stage',
            field=models.CharField(choices=[('before', 'Before (move-in)'), ('after', 'After (move-out)')], default='before', help_text='Condition photos: taken at move-in (before) or at move-out (after).', max_length=20),
        ),
    ]
